# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TreeCO2Sequestration
                                 A QGIS plugin
 This plugins predicts the tree above ground biomass by simply knowing the tree Diameter at Breast Height (DBH)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-13
        copyright            : (C) 2022 by Dr. K. Ilayaraja
        email                : ilayaraja22@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TreeCO2Sequestration class from file TreeCO2Sequestration.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .CO2_sequestration import TreeCO2Sequestration
    return TreeCO2Sequestration(iface)
